# Generated by Django 4.1.4 on 2023-01-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.CharField(db_collation='Turkish_CI_AS', db_column='CustomerID', max_length=11, primary_key=True, serialize=False)),
                ('contactpersonname', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='ContactPersonName', max_length=20, null=True)),
                ('phonenumber', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='PhoneNumber', max_length=14, null=True, unique=True)),
                ('email', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Email', max_length=35, null=True)),
                ('shippingaddress', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='ShippingAddress', max_length=60, null=True)),
            ],
            options={
                'db_table': 'CUSTOMER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('orderno', models.AutoField(db_column='OrderNo', primary_key=True, serialize=False)),
                ('orderinfo', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='OrderInfo', max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('datesold', models.DateField(blank=True, db_column='DateSold', null=True)),
                ('isplaced', models.BooleanField(blank=True, db_column='IsPlaced', null=True)),
            ],
            options={
                'db_table': 'CUSTOMER_ORDER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dno', models.SmallIntegerField(db_column='Dno', primary_key=True, serialize=False)),
                ('dfield', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='DField', max_length=50, null=True)),
                ('noofemployees', models.IntegerField(blank=True, db_column='NoOfEmployees', null=True)),
            ],
            options={
                'db_table': 'DEPARTMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('tckn', models.CharField(db_collation='Turkish_CI_AS', db_column='TCKN', max_length=11, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='FirstName', max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='LastName', max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Address', max_length=60, null=True)),
                ('birthdate', models.DateField(blank=True, db_column='Birthdate', null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('gender', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Gender', max_length=1, null=True)),
                ('phonenumber', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='PhoneNumber', max_length=14, null=True, unique=True)),
                ('startingdate', models.DateField(blank=True, db_column='StartingDate', null=True)),
                ('salary', models.FloatField(blank=True, db_column='Salary', null=True)),
                ('employeetype', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='EmployeeType', max_length=1, null=True)),
            ],
            options={
                'db_table': 'EMPLOYEE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('traderegistrationnumber', models.CharField(db_collation='Turkish_CI_AS', db_column='TradeRegistrationNumber', max_length=11, primary_key=True, serialize=False)),
                ('factoryname', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='FactoryName', max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Address', max_length=100, null=True)),
                ('phonenumber', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='PhoneNumber', max_length=14, null=True, unique=True)),
                ('fax', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Fax', max_length=12, null=True, unique=True)),
            ],
            options={
                'db_table': 'FACTORY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactoryProduct',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('productiondate', models.DateField(blank=True, db_column='ProductionDate', null=True)),
            ],
            options={
                'db_table': 'FACTORY_PRODUCT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.CharField(db_collation='Turkish_CI_AS', db_column='ItemID', max_length=11, primary_key=True, serialize=False)),
                ('itemtype', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='ItemType', max_length=150, null=True)),
                ('unitprice', models.FloatField(blank=True, db_column='UnitPrice', null=True)),
            ],
            options={
                'db_table': 'ITEM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierCompany',
            fields=[
                ('companyid', models.CharField(db_collation='Turkish_CI_AS', db_column='CompanyID', max_length=11, primary_key=True, serialize=False)),
                ('companyname', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='CompanyName', max_length=35, null=True)),
                ('address', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Address', max_length=60, null=True)),
                ('phonenumber', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='PhoneNumber', max_length=14, null=True, unique=True)),
            ],
            options={
                'db_table': 'SUPPLIER_COMPANY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplyRecord',
            fields=[
                ('supplyno', models.AutoField(db_column='SupplyNo', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('supplydate', models.DateField(blank=True, db_column='SupplyDate', null=True)),
            ],
            options={
                'db_table': 'SUPPLY_RECORD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpsProduct',
            fields=[
                ('productid', models.CharField(db_collation='Turkish_CI_AS', db_column='ProductID', max_length=20, primary_key=True, serialize=False)),
                ('productname', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='ProductName', max_length=100, null=True)),
                ('productprice', models.FloatField(blank=True, db_column='ProductPrice', null=True)),
                ('stock', models.IntegerField(blank=True, db_column='Stock', null=True)),
                ('engerysavingmode', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='EngerySavingMode', max_length=15, null=True)),
                ('conversiontechnology', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='ConversionTechnology', max_length=30, null=True)),
                ('standart', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Standart', max_length=60, null=True)),
                ('producttype', models.CharField(db_collation='Turkish_CI_AS', db_column='ProductType', max_length=3)),
            ],
            options={
                'db_table': 'UPS_PRODUCT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bluecollaremployee',
            fields=[
                ('tckn', models.OneToOneField(db_column='TCKN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.employee')),
                ('seniority', models.SmallIntegerField(blank=True, db_column='Seniority', null=True)),
            ],
            options={
                'db_table': 'BLUECOLLAREMPLOYEE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OneOnePhase',
            fields=[
                ('productid', models.OneToOneField(db_column='ProductID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.upsproduct')),
                ('frequencyconverterhz', models.FloatField(blank=True, db_column='FrequencyConverterHZ', null=True)),
            ],
            options={
                'db_table': 'ONE_ONE_PHASE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThreeOnePhase',
            fields=[
                ('productid', models.OneToOneField(db_column='ProductID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.upsproduct')),
                ('inputpowerfactor', models.FloatField(blank=True, db_column='InputPowerFactor', null=True)),
                ('inputvoltagerange', models.FloatField(blank=True, db_column='InputVoltageRange', null=True)),
            ],
            options={
                'db_table': 'THREE_ONE_PHASE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThreeThreePhase',
            fields=[
                ('productid', models.OneToOneField(db_column='ProductID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.upsproduct')),
                ('harmonicdistortionlevel', models.FloatField(blank=True, db_column='HarmonicDistortionLevel', null=True)),
                ('optinalpart', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='OptinalPart', max_length=500, null=True)),
            ],
            options={
                'db_table': 'THREE_THREE_PHASE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Whitecollaremployee',
            fields=[
                ('tckn', models.OneToOneField(db_column='TCKN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.employee')),
                ('gradutionmajor', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='GradutionMajor', max_length=75, null=True)),
            ],
            options={
                'db_table': 'WHITECOLLAREMPLOYEE',
                'managed': False,
            },
        ),
    ]
